AllCops:
  TargetRubyVersion: 2.4

# Gemspec block can have any length
Metrics/BlockLength:
  Exclude:
    - ghtml2pdf.gemspec

# Lenient line length
Metrics/LineLength:
  Max: 100

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# I like to have symbols always look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets
