language: ruby

dist: xenial

services:
  - xvfb

before_install:
  - sudo apt-get update
  # Provides libgirepository-1.0.so.1
  - sudo apt-get install libgirepository-1.0-1
  # Needed to avoid warnings about retrieving accessibility bus address
  - sudo apt-get install at-spi2-core
  # GIR data for Gtk 3
  - sudo apt-get install gir1.2-gtk-3.0
  # GIR data for GtkWebkit 3
  - sudo apt-get install gir1.2-webkit2-3.0
  # We shouldn't need these since we should use the so versions in the non-dev package
  - sudo apt-get install libwebkit2gtk-3.0-dev

cache:
  bundler: true

script: bundle exec rake

# - Run full test suite on MRI
# - Run rubocop on MRI 2.7
jobs:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: 2.7
      name: "RuboCop"
      before_install: []
      script: bundle exec rubocop

branches:
  only:
    - master
