sudo: required
dist: trusty
language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgirepository1.0-dev libwebkit2gtk-3.0-dev
  - sudo apt-get install -y gir1.2-gtk-3.0 gir1.2-webkit2-3.0
  - sudo apt-get install -y at-spi2-core avahi-daemon

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

branches:
  only:
    - master
